Task dev 6
GorshkovaYuliya/GIT-1 pull request #22
Opened 2017-06-30 18:51 UTC by GorshkovaYuliya

2017-07-02 08:59 UTC, AlexanderSoroka requested changes

2017-07-02 08:59 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/AnalizeSequence.java
> +          System.out.println("Your sequence is not non-decreasing");
Single responsibility principle violation - method must only check sequence (1 responsibility), not "check, verify and ouptut results" (3 responsibilities)

2017-07-03 20:59 UTC, AlexanderSoroka requested changes

2017-07-03 20:59 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/AnalizeSequence.java
> +        return;
What does this method do?

2017-07-03 20:59 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/SequenceModifided.java
> +      consoleRead.readConsole();
just read? not check?

2017-07-05 19:31 UTC, AlexanderSoroka requested changes

2017-07-05 19:31 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/SequenceModifided.java
> +    while(sequenceForCheck.length <= 1) {
Why do you allow user to re-enter sequence in case if it's too short but do not allow to re-enter if there are any invalid numbers (not a number, string etc)?
Re-write to have the same way to process all negative scenario

2017-07-05 19:31 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/ConsoleReading.java
> + * This class suggest user to enter  sequence.
Wrong comment

2017-07-05 19:31 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/SequenceModifided.java
> +    ConsoleReading consoleRead = new ConsoleReading();
declare variable as close to first usage as possible

2017-07-05 19:31 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/SequenceModifided.java
> +      if (sequenceCheck.determineSequence(sequenceForCheck) == true) {
useless == true

2017-07-07 10:02 UTC, AlexanderSoroka requested changes

2017-07-07 10:02 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/AnalizeSequence.java
> +   * @return false if the sequence is not non-decreasing
Only one `@return` statement should be specified

2017-07-07 10:05 UTC, GorshkovaYuliya commented on SequenceDividedOnClasses/AnalizeSequence.java
> +   * @return false if the sequence is not non-decreasing
Thank you, i'll fix it

2017-07-07 14:45 UTC, AlexanderSoroka requested changes

2017-07-07 14:45 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/AnalizeSequence.java
> +   * @return true if the sequence is non-decreasing
incomplete return value description, is not described when false is returned

2017-07-07 14:45 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/AnalizeSequence.java
> +   * @return true if the sequence consists only of numbers
see line 11

2017-07-07 14:45 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/SequenceModifided.java
> +    while(sequenceForCheck.length <= 1 || !(sequenceCheck.determineIsSequensCorrect(sequenceForCheck))) {
missed space

2017-07-07 14:45 UTC, AlexanderSoroka commented on SequenceDividedOnClasses/AnalizeSequence.java
> +  public boolean determineSequence(String[] args) {
I would say better name is "isNonDecreasing"

2017-07-11 10:51 UTC, AlexanderSoroka approved these changes

2017-07-11 11:14 UTC, merged